#!/bin/sh

pnpm exec lint-staged

# Check for sensitive files in the staging area
staged_files=$(git diff --cached --name-only)

if echo "$staged_files" | grep -q -E "(.env|.env.dev|.env.prod|.env.development|.env.production)$"; then
  echo "❌ ERROR: You are trying to commit a .env file!"
  echo "Please run 'git rm --cached <file>' and add it to .gitignore."
  exit 1
fi

if echo "$staged_files" | grep -q "google-services.json"; then
  echo "❌ ERROR: You are trying to commit a google-services.json file!"
  echo "Please run 'git rm --cached google-services.json' and add it to .gitignore."
  exit 1
fi

if echo "$staged_files" | grep -q "GoogleService-Info.plist"; then
  echo "❌ ERROR: You are trying to commit a GoogleService-Info.plist file!"
  echo "Please run 'git rm --cached GoogleService-Info.plist' and add it to .gitignore."
  exit 1
fi
